# Generated by Django 4.2.2 on 2023-06-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('desc', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to='film/img')),
            ],
        ),
        migrations.DeleteModel(
            name='Film',
        ),
    ]
